# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: privacy-sandbox-attestations/privacy_sandbox_attestations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?privacy-sandbox-attestations/privacy_sandbox_attestations.proto\x12\x0fprivacy_sandbox\"\xf5\x03\n\x1fPrivacySandboxAttestationsProto\x12J\n\x08\x61ll_apis\x18\x01 \x03(\x0e\x32\x38.privacy_sandbox.PrivacySandboxAttestationsGatedAPIProto\x12#\n\x1bsites_attested_for_all_apis\x18\x02 \x03(\t\x12\x61\n\x11site_attestations\x18\x03 \x03(\x0b\x32\x46.privacy_sandbox.PrivacySandboxAttestationsProto.SiteAttestationsEntry\x1ar\n\x1fPrivacySandboxAttestedAPIsProto\x12O\n\rattested_apis\x18\x01 \x03(\x0e\x32\x38.privacy_sandbox.PrivacySandboxAttestationsGatedAPIProto\x1a\x89\x01\n\x15SiteAttestationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12_\n\x05value\x18\x02 \x01(\x0b\x32P.privacy_sandbox.PrivacySandboxAttestationsProto.PrivacySandboxAttestedAPIsProto:\x02\x38\x01*\xbb\x01\n\'PrivacySandboxAttestationsGatedAPIProto\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06TOPICS\x10\x01\x12\x16\n\x12PROTECTED_AUDIENCE\x10\x02\x12\x17\n\x13PRIVATE_AGGREGATION\x10\x03\x12\x19\n\x15\x41TTRIBUTION_REPORTING\x10\x04\x12\x12\n\x0eSHARED_STORAGE\x10\x05\x12\x17\n\x13\x46\x45NCED_STORAGE_READ\x10\x06\x62\x06proto3')

_PRIVACYSANDBOXATTESTATIONSGATEDAPIPROTO = DESCRIPTOR.enum_types_by_name['PrivacySandboxAttestationsGatedAPIProto']
PrivacySandboxAttestationsGatedAPIProto = enum_type_wrapper.EnumTypeWrapper(_PRIVACYSANDBOXATTESTATIONSGATEDAPIPROTO)
UNKNOWN = 0
TOPICS = 1
PROTECTED_AUDIENCE = 2
PRIVATE_AGGREGATION = 3
ATTRIBUTION_REPORTING = 4
SHARED_STORAGE = 5
FENCED_STORAGE_READ = 6


_PRIVACYSANDBOXATTESTATIONSPROTO = DESCRIPTOR.message_types_by_name['PrivacySandboxAttestationsProto']
_PRIVACYSANDBOXATTESTATIONSPROTO_PRIVACYSANDBOXATTESTEDAPISPROTO = _PRIVACYSANDBOXATTESTATIONSPROTO.nested_types_by_name['PrivacySandboxAttestedAPIsProto']
_PRIVACYSANDBOXATTESTATIONSPROTO_SITEATTESTATIONSENTRY = _PRIVACYSANDBOXATTESTATIONSPROTO.nested_types_by_name['SiteAttestationsEntry']
PrivacySandboxAttestationsProto = _reflection.GeneratedProtocolMessageType('PrivacySandboxAttestationsProto', (_message.Message,), {

  'PrivacySandboxAttestedAPIsProto' : _reflection.GeneratedProtocolMessageType('PrivacySandboxAttestedAPIsProto', (_message.Message,), {
    'DESCRIPTOR' : _PRIVACYSANDBOXATTESTATIONSPROTO_PRIVACYSANDBOXATTESTEDAPISPROTO,
    '__module__' : 'privacy_sandbox_attestations.privacy_sandbox_attestations_pb2'
    # @@protoc_insertion_point(class_scope:privacy_sandbox.PrivacySandboxAttestationsProto.PrivacySandboxAttestedAPIsProto)
    })
  ,

  'SiteAttestationsEntry' : _reflection.GeneratedProtocolMessageType('SiteAttestationsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PRIVACYSANDBOXATTESTATIONSPROTO_SITEATTESTATIONSENTRY,
    '__module__' : 'privacy_sandbox_attestations.privacy_sandbox_attestations_pb2'
    # @@protoc_insertion_point(class_scope:privacy_sandbox.PrivacySandboxAttestationsProto.SiteAttestationsEntry)
    })
  ,
  'DESCRIPTOR' : _PRIVACYSANDBOXATTESTATIONSPROTO,
  '__module__' : 'privacy_sandbox_attestations.privacy_sandbox_attestations_pb2'
  # @@protoc_insertion_point(class_scope:privacy_sandbox.PrivacySandboxAttestationsProto)
  })
_sym_db.RegisterMessage(PrivacySandboxAttestationsProto)
_sym_db.RegisterMessage(PrivacySandboxAttestationsProto.PrivacySandboxAttestedAPIsProto)
_sym_db.RegisterMessage(PrivacySandboxAttestationsProto.SiteAttestationsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRIVACYSANDBOXATTESTATIONSPROTO_SITEATTESTATIONSENTRY._options = None
  _PRIVACYSANDBOXATTESTATIONSPROTO_SITEATTESTATIONSENTRY._serialized_options = b'8\001'
  _PRIVACYSANDBOXATTESTATIONSGATEDAPIPROTO._serialized_start=589
  _PRIVACYSANDBOXATTESTATIONSGATEDAPIPROTO._serialized_end=776
  _PRIVACYSANDBOXATTESTATIONSPROTO._serialized_start=85
  _PRIVACYSANDBOXATTESTATIONSPROTO._serialized_end=586
  _PRIVACYSANDBOXATTESTATIONSPROTO_PRIVACYSANDBOXATTESTEDAPISPROTO._serialized_start=332
  _PRIVACYSANDBOXATTESTATIONSPROTO_PRIVACYSANDBOXATTESTEDAPISPROTO._serialized_end=446
  _PRIVACYSANDBOXATTESTATIONSPROTO_SITEATTESTATIONSENTRY._serialized_start=449
  _PRIVACYSANDBOXATTESTATIONSPROTO_SITEATTESTATIONSENTRY._serialized_end=586
# @@protoc_insertion_point(module_scope)
